// Generated by gencpp from file letsgooo/TargetPosition.msg
// DO NOT EDIT!


#ifndef LETSGOOO_MESSAGE_TARGETPOSITION_H
#define LETSGOOO_MESSAGE_TARGETPOSITION_H

#include <ros/service_traits.h>


#include <letsgooo/TargetPositionRequest.h>
#include <letsgooo/TargetPositionResponse.h>


namespace letsgooo
{

struct TargetPosition
{

typedef TargetPositionRequest Request;
typedef TargetPositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TargetPosition
} // namespace letsgooo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::letsgooo::TargetPosition > {
  static const char* value()
  {
    return "dd76aff00a72b33e8d77950fa07ebddf";
  }

  static const char* value(const ::letsgooo::TargetPosition&) { return value(); }
};

template<>
struct DataType< ::letsgooo::TargetPosition > {
  static const char* value()
  {
    return "letsgooo/TargetPosition";
  }

  static const char* value(const ::letsgooo::TargetPosition&) { return value(); }
};


// service_traits::MD5Sum< ::letsgooo::TargetPositionRequest> should match
// service_traits::MD5Sum< ::letsgooo::TargetPosition >
template<>
struct MD5Sum< ::letsgooo::TargetPositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::letsgooo::TargetPosition >::value();
  }
  static const char* value(const ::letsgooo::TargetPositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::letsgooo::TargetPositionRequest> should match
// service_traits::DataType< ::letsgooo::TargetPosition >
template<>
struct DataType< ::letsgooo::TargetPositionRequest>
{
  static const char* value()
  {
    return DataType< ::letsgooo::TargetPosition >::value();
  }
  static const char* value(const ::letsgooo::TargetPositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::letsgooo::TargetPositionResponse> should match
// service_traits::MD5Sum< ::letsgooo::TargetPosition >
template<>
struct MD5Sum< ::letsgooo::TargetPositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::letsgooo::TargetPosition >::value();
  }
  static const char* value(const ::letsgooo::TargetPositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::letsgooo::TargetPositionResponse> should match
// service_traits::DataType< ::letsgooo::TargetPosition >
template<>
struct DataType< ::letsgooo::TargetPositionResponse>
{
  static const char* value()
  {
    return DataType< ::letsgooo::TargetPosition >::value();
  }
  static const char* value(const ::letsgooo::TargetPositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LETSGOOO_MESSAGE_TARGETPOSITION_H
